/**
 * The hard exit at the stop deadline (lifemodel-ctc.1.2).
 *
 * The graceful stop is BEST EFFORT and BOUNDED: whatever still hangs at the
 * ONE deadline - a stalled intake stop, a stalled tick, a hung send, a stalled
 * storage flush - is abandoned and the process exits with a non-zero code,
 * naming what was still pending. Nothing is lost by leaving: inbound messages
 * are carried by the durable inbound log, internal signals are regenerated by
 * the ticks of the next run.
 *
 * The timer is armed by src/index.ts around `container.shutdown()`, exactly
 * as the helper below does it; the EXIT is injected, so no test kills vitest.
 */
import { afterEach, describe, expect, it } from 'vitest';

import type { StopProgress } from '../../src/core/container.js';
import { shutdownSequence } from '../../src/core/container.js';
import { createUserMessageSignal } from '../../src/types/signal.js';
import { armStopDeadlineExit, type StopPendingReport } from '../../src/core/hard-exit.js';
import type { Logger } from '../../src/types/logger.js';

import {
  makeDeferred,
  makeScratchDir,
  openStorage,
  rmDir,
  startInstance,
  stopInstance,
  thoughtSignal,
  waitFor,
} from '../helpers/core-loop-drain-harness.js';
import { createTestLogger, recordingLogger, type RecordedLog } from '../helpers/test-logger.js';

/** The deadline every test here arms: real enough to mean something, short enough to run. */
const BUDGET_MS = 150;

const DEADLINE_MESSAGE = 'Stop deadline reached: the process exits now, whatever is still pending';

const scratchRoots: string[] = [];

async function freshScratch(prefix: string): Promise<string> {
  const root = await makeScratchDir(prefix);
  scratchRoots.push(root);
  return root;
}

afterEach(async () => {
  for (const root of scratchRoots.splice(0)) {
    await rmDir(root);
  }
});

/** An injected exit that records its code instead of killing the test runner. */
function exitSpy(): {
  codes: number[];
  arm: (
    logger: Logger,
    pending: () => StopPendingReport & { step: string },
    budgetMs?: number
  ) => { disarm: () => void };
} {
  const codes: number[] = [];
  return {
    codes,
    arm: (logger, pending, budgetMs = BUDGET_MS) =>
      armStopDeadlineExit({ logger, budgetMs, pending, exit: (code) => codes.push(code) }),
  };
}

/** The one error line the hard exit wrote, if it wrote one. */
function deadlineLine(recorded: RecordedLog[]): RecordedLog | undefined {
  return recorded.find((c) => c.level === 'error' && c.msg === DEADLINE_MESSAGE);
}

/** A core-loop double: the sequence only calls stop() on it. */
function loopDouble(steps: string[], report: Partial<StopPendingReport> = {}) {
  return {
    stop: async (): Promise<void> => {
      steps.push('coreLoop.stop');
    },
    closeDurableWrites: (): void => {
      steps.push('coreLoop.closeDurableWrites');
    },
    stopReport: (): StopPendingReport => ({
      loopStopped: true,
      tickInFlight: false,
      schedulerInFlight: false,
      turnInFlight: false,
      sendsOutstanding: 0,
      queuedSignals: 0,
      ...report,
    }),
  };
}

const noopShutdown = { shutdown: async (): Promise<void> => undefined };
const noopFlush = { flush: async (): Promise<void> => undefined };

describe('hard exit at the stop deadline (lifemodel-ctc.1.2)', () => {
  it('a stalled intake stop: the exit is requested at the deadline and the log names the step', async () => {
    const recorded: RecordedLog[] = [];
    const logger = recordingLogger(createTestLogger('warn'), recorded);
    const spy = exitSpy();
    const progress: StopProgress = { step: 'done' };
    const steps: string[] = [];
    const channel = {
      name: 'test',
      stopIntake: (): Promise<void> => {
        steps.push('channel.stopIntake');
        return new Promise<void>(() => undefined); // never settles
      },
      stop: async (): Promise<void> => {
        steps.push('channel.stop');
      },
    };
    const coreLoop = loopDouble(steps);

    const armed = spy.arm(logger, () => ({ step: progress.step, ...coreLoop.stopReport() }));
    // NOT awaited: the stalled intake stop never returns - that is the point.
    void shutdownSequence({
      logger,
      deadline: Date.now() + BUDGET_MS,
      channels: [channel] as never,
      coreLoop: coreLoop as never,
      storage: noopShutdown as never,
      progress,
      stateManager: noopShutdown as never,
      recipientRegistry: noopFlush as never,
      ackRegistry: noopFlush as never,
    });

    await waitFor(() => spy.codes.length === 1, 'the hard exit was requested at the deadline');
    armed.disarm();

    expect(spy.codes).toEqual([1]);
    expect(steps).toEqual(['channel.stopIntake']); // nothing after it ever ran
    const line = deadlineLine(recorded);
    expect(line).toBeDefined();
    expect((line?.obj['pending'] as { step: string }).step).toBe('intake_stop');
  });

  it('a stalled storage flush: the exit is requested at the deadline and the log names the step', async () => {
    const recorded: RecordedLog[] = [];
    const logger = recordingLogger(createTestLogger('warn'), recorded);
    const spy = exitSpy();
    const progress: StopProgress = { step: 'done' };
    const steps: string[] = [];
    const channel = {
      name: 'test',
      stopIntake: async (): Promise<void> => {
        steps.push('channel.stopIntake');
      },
      stop: async (): Promise<void> => {
        steps.push('channel.stop');
      },
    };
    const coreLoop = loopDouble(steps);

    const armed = spy.arm(logger, () => ({ step: progress.step, ...coreLoop.stopReport() }));
    void shutdownSequence({
      logger,
      deadline: Date.now() + BUDGET_MS,
      channels: [channel] as never,
      coreLoop: coreLoop as never,
      storage: { shutdown: () => new Promise<void>(() => undefined) } as never,
      progress,
      stateManager: noopShutdown as never,
      recipientRegistry: noopFlush as never,
      ackRegistry: noopFlush as never,
    });

    await waitFor(() => spy.codes.length === 1, 'the hard exit was requested at the deadline');
    armed.disarm();

    expect(spy.codes).toEqual([1]);
    expect(steps).toEqual([
      'channel.stopIntake',
      'coreLoop.stop',
      'channel.stop',
      'coreLoop.closeDurableWrites',
    ]);
    const line = deadlineLine(recorded);
    expect((line?.obj['pending'] as { step: string }).step).toBe('storage_flush');
  });

  it('a stalled tick: the exit is requested at the deadline and the log names the tick in flight', async () => {
    const storagePath = await freshScratch('ctc-hard-tick-');
    const recorded: RecordedLog[] = [];
    const logger = recordingLogger(createTestLogger('warn'), recorded);
    const h1 = await startInstance(storagePath, {
      cognitionMode: 'immediate',
      drainTimeoutMs: BUDGET_MS,
      logger,
    });
    // A tick that hangs INSIDE its body (it already took its batch): the stop
    // bounds its wait by the deadline and never gets the tick back.
    const release = makeDeferred<void>();
    h1.aggregation.processGate = release.promise;
    h1.coreLoop.pushSignal(thoughtSignal('taken by the hung tick', h1.recipientId));
    await waitFor(() => h1.aggregation.batches.length > 0, 'the tick took the batch');

    const spy = exitSpy();
    const armed = spy.arm(logger, () => ({ step: 'loop_drain', ...h1.coreLoop.stopReport() }));
    await stopInstance(h1, await openStorage(storagePath, logger));
    await waitFor(() => spy.codes.length === 1, 'the hard exit was requested at the deadline');
    armed.disarm();

    expect(spy.codes).toEqual([1]);
    const line = deadlineLine(recorded);
    const pending = line?.obj['pending'] as StopPendingReport & { step: string };
    expect(pending.step).toBe('loop_drain');
    expect(pending.tickInFlight).toBe(true);
    release.resolve();
  });

  it('a hung send: the exit is requested at the deadline and the log names the outstanding send', async () => {
    const storagePath = await freshScratch('ctc-hard-send-');
    const recorded: RecordedLog[] = [];
    const logger = recordingLogger(createTestLogger('warn'), recorded);
    const h1 = await startInstance(storagePath, {
      cognitionMode: 'hang',
      drainTimeoutMs: BUDGET_MS,
      logger,
    });
    h1.coreLoop.pushSignal(thoughtSignal('turn trigger', h1.recipientId));
    await waitFor(() => h1.cognition.calls.length === 1, 'cognition started');

    // the send never returns: the stop can neither deliver nor report it
    h1.channel.sendGate = new Promise<void>(() => undefined);
    h1.cognition.settleAll({
      confidence: 1,
      intents: [
        { type: 'SEND_MESSAGE', payload: { recipientId: h1.recipientId, text: 'the answer' } },
      ],
      response: undefined,
    });

    const spy = exitSpy();
    const armed = spy.arm(logger, () => ({ step: 'loop_drain', ...h1.coreLoop.stopReport() }));
    await stopInstance(h1, await openStorage(storagePath, logger));
    await waitFor(() => spy.codes.length === 1, 'the hard exit was requested at the deadline');
    armed.disarm();

    expect(spy.codes).toEqual([1]);
    expect(h1.channel.sent).toEqual([]);
    const line = deadlineLine(recorded);
    const pending = line?.obj['pending'] as StopPendingReport & { step: string };
    expect(pending.sendsOutstanding).toBe(1);
    h1.cognition.settleAll();
  });

  it('REAL cognition: a turn that overruns the drain leaves the process at the deadline, named', async () => {
    const storagePath = await freshScratch('ctc-hard-real-');
    const recorded: RecordedLog[] = [];
    const logger = recordingLogger(createTestLogger('warn'), recorded);
    const h1 = await startInstance(storagePath, {
      cognitionMode: 'real-scripted',
      hang: true, // the LLM never answers: the turn is in flight
      script: [{ content: 'never reached' }],
      drainTimeoutMs: BUDGET_MS,
      logger,
    });
    h1.coreLoop.pushSignal(
      createUserMessageSignal({
        text: 'a question the real loop never finishes',
        chatId: 'chat-42',
        recipientId: h1.recipientId,
      })
    );
    await waitFor(() => h1.cognition.provider.requests.length === 1, 'the real turn is in flight');

    const spy = exitSpy();
    const armed = spy.arm(logger, () => ({ step: 'loop_drain', ...h1.coreLoop.stopReport() }));
    await stopInstance(h1, await openStorage(storagePath, logger));
    await waitFor(() => spy.codes.length === 1, 'the hard exit was requested at the deadline');
    armed.disarm();

    expect(spy.codes).toEqual([1]);
    const line = deadlineLine(recorded);
    const pending = line?.obj['pending'] as StopPendingReport & { step: string };
    expect(pending.step).toBe('loop_drain');
    expect(pending.turnInFlight).toBe(true);
    h1.cognition.settleHangingTurn();
  });

  it('a stop that finishes in time disarms the timer: the process exits normally', async () => {
    const storagePath = await freshScratch('ctc-hard-clean-');
    const logger = createTestLogger('warn');
    const h1 = await startInstance(storagePath, {
      cognitionMode: 'immediate',
      drainTimeoutMs: BUDGET_MS,
      logger,
    });
    const spy = exitSpy();
    const armed = spy.arm(logger, () => ({ step: 'done', ...h1.coreLoop.stopReport() }));

    await stopInstance(h1, await openStorage(storagePath, logger));
    armed.disarm();

    // the timer would have fired inside this window
    await new Promise((r) => setTimeout(r, BUDGET_MS * 2));
    expect(spy.codes).toEqual([]);
    expect(h1.channel.fullyStopped).toBe(true);
  });
});

describe('StopReport: what the hard exit names (lifemodel-ctc.1.2)', () => {
  it('names a turn in flight, an outstanding send and a queued signal', async () => {
    const storagePath = await freshScratch('ctc-stopreport-');
    const h1 = await startInstance(storagePath, {
      cognitionMode: 'hang',
      drainTimeoutMs: 400,
    });
    h1.coreLoop.pushSignal(thoughtSignal('turn trigger', h1.recipientId));
    await waitFor(() => h1.cognition.calls.length === 1, 'cognition started');
    // accepted while the turn runs: it sits in the queue, unprocessed
    h1.coreLoop.pushSignal(thoughtSignal('queued behind the turn'));
    await waitFor(() => h1.coreLoop.pendingSignalCount() === 1, 'the second signal is queued');

    const running = h1.coreLoop.stopReport();
    expect(running.loopStopped).toBe(false);
    expect(running.turnInFlight).toBe(true);
    expect(running.queuedSignals).toBe(1);

    h1.channel.sendGate = new Promise<void>(() => undefined);
    h1.cognition.settleAll({
      confidence: 1,
      intents: [
        { type: 'SEND_MESSAGE', payload: { recipientId: h1.recipientId, text: 'the answer' } },
      ],
      response: undefined,
    });

    const stopping = stopInstance(h1, await openStorage(storagePath));
    await waitFor(() => h1.coreLoop.stopReport().sendsOutstanding === 1, 'the send is outstanding');
    expect(h1.coreLoop.stopReport().loopStopped).toBe(true);
    await stopping;
    h1.cognition.settleAll();
  });
});
