/**
 * Hard exit at the stop deadline (lifemodel-ctc.1.2).
 *
 * The graceful stop is best effort and BOUNDED: past the ONE deadline
 * (`CoreLoopConfig.shutdownDrainTimeoutMs`, default 90 s) whatever still hangs
 * - a stalled intake stop, a stalled tick, a hung send, a stalled storage
 * flush - is abandoned and the process leaves. Nothing is lost by leaving:
 * inbound messages are carried by the durable inbound log (their commit
 * flushes on its own) and internal signals are regenerated by the next run's
 * ticks.
 *
 * `src/index.ts` arms this timer when the shutdown starts and disarms it when
 * `container.shutdown()` resolved; the EXIT is injectable so a test can prove
 * the deadline is honoured without killing the test runner.
 */
import type { Logger } from '../types/logger.js';

/**
 * What the stop still had in flight when the deadline hit, as one object: the
 * step of the shutdown sequence that had not finished, plus the core loop's
 * live work (see CoreLoop.stopReport). It is what the hard exit LOGS.
 */
export interface StopPendingReport {
  /** The loop's tick timer is off: no further signal processing starts. */
  loopStopped: boolean;
  /** A tick body is still running - a stalled tick hangs here. */
  tickInFlight: boolean;
  /** The scheduler callback is still running. */
  schedulerInFlight: boolean;
  /** A COGNITION turn is still awaited (the drain waits for it). */
  turnInFlight: boolean;
  /** SEND_MESSAGE chains that have not settled - a hung send. */
  sendsOutstanding: number;
  /** Signals accepted but never processed (dropped at the stop). */
  queuedSignals: number;
}

/** The process exit; injected by tests so an injected run never exits. */
export type ExitFn = (code: number) => void;

/**
 * The exit code of a stop that hit its deadline: the stop did not finish, so
 * the run does not end cleanly (same code as a shutdown that reported an
 * error, `src/index.ts`).
 */
export const STOP_DEADLINE_EXIT_CODE = 1;

/** The one error line the hard exit writes, so operators can grep for it. */
export const STOP_DEADLINE_MESSAGE =
  'Stop deadline reached: the process exits now, whatever is still pending';

export interface StopDeadlineExitOptions {
  logger: Logger;
  /** The stop budget in ms: the timer fires this long after arming. */
  budgetMs: number;
  /**
   * Read at the deadline, never earlier: what the stop had not finished. The
   * caller composes it from the shutdown sequence's step and the loop's
   * report (see StopPendingReport).
   */
  pending: () => StopPendingReport & { step: string };
  /** Defaults to `process.exit`; tests inject a recorder. */
  exit?: ExitFn;
  /** Defaults to STOP_DEADLINE_EXIT_CODE. */
  code?: number;
}

export interface ArmedStopDeadlineExit {
  /** The stop finished in time: the timer will never fire. */
  disarm: () => void;
}

/**
 * Arm the hard exit `budgetMs` from now. The timer stays REFERENCED until it
 * is disarmed, and that is the point: it is the only thing that makes a hung
 * shutdown end. A pending Promise keeps nothing alive, so an UNREF'D timer
 * lets Node leave with code 0 before the deadline - measured on a real child
 * process (review round 1, finding 1; tests/fixtures/stop-deadline-child.ts).
 * The caller disarms it as soon as the stop resolved, so a healthy process is
 * not held open by it.
 *
 * At the deadline the timer writes one error line naming what is still pending
 * and calls the exit with a non-zero code, whatever the stop is doing then.
 */
export function armStopDeadlineExit(options: StopDeadlineExitOptions): ArmedStopDeadlineExit {
  const code = options.code ?? STOP_DEADLINE_EXIT_CODE;
  const exit: ExitFn =
    options.exit ??
    ((value: number): void => {
      process.exit(value);
    });
  const timer = setTimeout(() => {
    options.logger.error(
      { deadlineMs: options.budgetMs, pending: options.pending() },
      STOP_DEADLINE_MESSAGE
    );
    exit(code);
  }, options.budgetMs);
  return {
    disarm: (): void => {
      clearTimeout(timer);
    },
  };
}
